"""initial_portfolio_and_asset_schema

Revision ID: 4a18fbab5681
Revises: 
Create Date: 2026-07-10 10:15:28.642380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a18fbab5681'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('is_shariah', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('launch_date', sa.Date(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', name='uq_asset_symbol')
    )
    op.create_index('ix_asset_exchange', 'asset', ['exchange'], unique=False)
    op.create_index('ix_asset_is_shariah', 'asset', ['is_shariah'], unique=False)
    op.create_index('ix_asset_status', 'asset', ['status'], unique=False)
    op.create_index('ix_asset_type', 'asset', ['asset_type'], unique=False)
    op.create_table('benchmark',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('benchmark_type', sa.String(length=50), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_benchmark_name')
    )
    op.create_table('fund_category',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_fund_category_name')
    )
    op.create_table('portfolio',
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('risk_profile', sa.String(length=50), nullable=False),
    sa.Column('investment_preference', sa.String(length=50), nullable=False),
    sa.Column('investment_objective', sa.String(length=50), nullable=False),
    sa.Column('investment_horizon', sa.String(length=50), nullable=False),
    sa.Column('monthly_sip', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_portfolio_owner_name')
    )
    op.create_index('ix_portfolio_owner_id', 'portfolio', ['owner_id'], unique=False)
    op.create_index('ix_portfolio_status', 'portfolio', ['status'], unique=False)
    op.create_table('sector',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('cyclical', sa.Boolean(), nullable=False),
    sa.Column('interest_rate_sensitive', sa.Boolean(), nullable=False),
    sa.Column('inflation_sensitive', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_sector_name')
    )
    op.create_table('holding',
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=19, scale=6), nullable=False),
    sa.Column('average_cost', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('unrealized_gain', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('realized_gain', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('allocation_percentage', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_price_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'asset_id', name='uq_holding_portfolio_asset')
    )
    op.create_index('ix_holding_asset_id', 'holding', ['asset_id'], unique=False)
    op.create_index('ix_holding_portfolio_id', 'holding', ['portfolio_id'], unique=False)
    op.create_index('ix_holding_status', 'holding', ['status'], unique=False)
    op.create_table('investment_goal',
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('monthly_contribution', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('risk_preference', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_goal_portfolio_id', 'investment_goal', ['portfolio_id'], unique=False)
    op.create_index('ix_goal_status', 'investment_goal', ['status'], unique=False)
    op.create_table('mutual_fund',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('management_company', sa.String(length=255), nullable=True),
    sa.Column('fund_category_id', sa.Uuid(), nullable=True),
    sa.Column('benchmark_id', sa.Uuid(), nullable=True),
    sa.Column('expense_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('front_load', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('back_load', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('management_fee', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('minimum_investment', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('minimum_sip', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('aum', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('cash_percentage', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('equity_percentage', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('debt_percentage', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('dividend_policy', sa.String(length=50), nullable=True),
    sa.Column('dividend_frequency', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('factsheet_url', sa.String(length=500), nullable=True),
    sa.Column('prospectus_url', sa.String(length=500), nullable=True),
    sa.Column('last_nav_update', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['benchmark_id'], ['benchmark.id'], ),
    sa.ForeignKeyConstraint(['fund_category_id'], ['fund_category.id'], ),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_index('ix_mutual_fund_benchmark', 'mutual_fund', ['benchmark_id'], unique=False)
    op.create_index('ix_mutual_fund_category', 'mutual_fund', ['fund_category_id'], unique=False)
    op.create_table('nav_history',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('nav_date', sa.Date(), nullable=False),
    sa.Column('nav', sa.Numeric(precision=19, scale=6), nullable=False),
    sa.Column('adjusted_nav', sa.Numeric(precision=19, scale=6), nullable=True),
    sa.Column('daily_return', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('dividend', sa.Numeric(precision=19, scale=6), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'nav_date', name='uq_nav_asset_date')
    )
    op.create_index('ix_nav_asset_id', 'nav_history', ['asset_id'], unique=False)
    op.create_index('ix_nav_date', 'nav_history', ['nav_date'], unique=False)
    op.create_table('portfolio_snapshot',
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('investment_value', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('cash_value', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('daily_return', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('monthly_return', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('yearly_return', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('xirr', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('cagr', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('volatility', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('drawdown', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('sortino_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('allocation_json', sa.JSON(), nullable=True),
    sa.Column('sector_allocation_json', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'snapshot_date', name='uq_snapshot_portfolio_date')
    )
    op.create_index('ix_snapshot_date', 'portfolio_snapshot', ['snapshot_date'], unique=False)
    op.create_index('ix_snapshot_portfolio_id', 'portfolio_snapshot', ['portfolio_id'], unique=False)
    op.create_table('price_history',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('high_price', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('low_price', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('adjusted_close', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('volume', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'price_date', name='uq_price_asset_date')
    )
    op.create_index('ix_price_asset_id', 'price_history', ['asset_id'], unique=False)
    op.create_index('ix_price_date', 'price_history', ['price_date'], unique=False)
    op.create_table('stock',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('sector_id', sa.Uuid(), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('free_float', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('shares_outstanding', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('eps', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('pe', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('pbv', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('roe', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('roa', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('debt_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('last_financial_update', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_index('ix_stock_industry', 'stock', ['industry'], unique=False)
    op.create_index('ix_stock_market_cap', 'stock', ['market_cap'], unique=False)
    op.create_index('ix_stock_sector', 'stock', ['sector_id'], unique=False)
    op.create_table('transaction',
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('holding_id', sa.Uuid(), nullable=True),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('units', sa.Numeric(precision=19, scale=6), nullable=False),
    sa.Column('price', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('fees', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('taxes', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['holding_id'], ['holding.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transaction_asset_id', 'transaction', ['asset_id'], unique=False)
    op.create_index('ix_transaction_date', 'transaction', ['transaction_date'], unique=False)
    op.create_index('ix_transaction_portfolio_date', 'transaction', ['portfolio_id', 'transaction_date'], unique=False)
    op.create_index('ix_transaction_portfolio_id', 'transaction', ['portfolio_id'], unique=False)
    op.create_index('ix_transaction_status', 'transaction', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transaction_status', table_name='transaction')
    op.drop_index('ix_transaction_portfolio_id', table_name='transaction')
    op.drop_index('ix_transaction_portfolio_date', table_name='transaction')
    op.drop_index('ix_transaction_date', table_name='transaction')
    op.drop_index('ix_transaction_asset_id', table_name='transaction')
    op.drop_table('transaction')
    op.drop_index('ix_stock_sector', table_name='stock')
    op.drop_index('ix_stock_market_cap', table_name='stock')
    op.drop_index('ix_stock_industry', table_name='stock')
    op.drop_table('stock')
    op.drop_index('ix_price_date', table_name='price_history')
    op.drop_index('ix_price_asset_id', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index('ix_snapshot_portfolio_id', table_name='portfolio_snapshot')
    op.drop_index('ix_snapshot_date', table_name='portfolio_snapshot')
    op.drop_table('portfolio_snapshot')
    op.drop_index('ix_nav_date', table_name='nav_history')
    op.drop_index('ix_nav_asset_id', table_name='nav_history')
    op.drop_table('nav_history')
    op.drop_index('ix_mutual_fund_category', table_name='mutual_fund')
    op.drop_index('ix_mutual_fund_benchmark', table_name='mutual_fund')
    op.drop_table('mutual_fund')
    op.drop_index('ix_goal_status', table_name='investment_goal')
    op.drop_index('ix_goal_portfolio_id', table_name='investment_goal')
    op.drop_table('investment_goal')
    op.drop_index('ix_holding_status', table_name='holding')
    op.drop_index('ix_holding_portfolio_id', table_name='holding')
    op.drop_index('ix_holding_asset_id', table_name='holding')
    op.drop_table('holding')
    op.drop_table('sector')
    op.drop_index('ix_portfolio_status', table_name='portfolio')
    op.drop_index('ix_portfolio_owner_id', table_name='portfolio')
    op.drop_table('portfolio')
    op.drop_table('fund_category')
    op.drop_table('benchmark')
    op.drop_index('ix_asset_type', table_name='asset')
    op.drop_index('ix_asset_status', table_name='asset')
    op.drop_index('ix_asset_is_shariah', table_name='asset')
    op.drop_index('ix_asset_exchange', table_name='asset')
    op.drop_table('asset')
    # ### end Alembic commands ###
